---
abstract: 'Parse iCalendar files into a data structure'
author:
  - 'Rick Frankel, cpan@rickster.com'
build_requires:
  FreezeThaw: 0.43
  Test::More: 0.54
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: iCal-Parser
provides:
  iCal::Parser:
    file: lib/iCal/Parser.pm
    version: 1.20
requires:
  DateTime::Format::ICal: 0.08
  File::Basename: 0
  IO::File: 1.1
  IO::String: 0
  Text::vFile::asData: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 1.20
